name = "JuliaStockAnalysis"
license = "MIT"
authors = ["Your Name <you@example.com>"]
description = "A Julia project to analyze stock market trends using YFinance.jl"
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
YFinance = "e4b3b0a2-f9a3-42f3-aabb-32142cceaf77"
